data:
  symbols: ['AAPL', 'GOOGL', 'MSFT', 'TSLA']
  start_date: '2021-01-01'
  end_date: '2025-01-01'
  train_split: 0.8
  
arima:
  p_range: [0, 4]
  d_range: [0, 2]
  q_range: [0, 4]
  
lstm:
  sequence_length: 60
  hidden_dim: 50
  num_layers: 2
  dropout: 0.2
  learning_rate: 0.001
  batch_size: 32
  epochs: 100
  
mlflow:
  experiment_name: 'stock_price_prediction'
  tracking_uri: 'mlruns'
